### PR TITLE
Add Feature: Construct middleware by enforcer

### PR DESCRIPTION
**Pull request by suleymanozev**
Construct middleware by enforcer

### CODE REVIEW

**Comment by hsluoyz** [comment]
@arsmn

**Comment by suleymanozev** [comment]
@arsmn Why don't you merge? Is there something I'm doing wrong?

**Comment by arsmn** [comment]
Hi @suleymanozev 
I'm so sorry about that, I completely forgot that.
Your commit has break change on New function.
Please keep existing New function.
Also you changed go module name.
Fiber has changed its Handler signature since V2, so update your commit and I will merge that.
Thanks

**Comment by suleymanozev** [comment]
@arsmn Of course, I'm making the changes immediately. Thanks

**Comment by hsluoyz** [comment]
Thank you both!

**Pull request closed without merging**
